import NextHead from 'next/head'

export function Head() {
  return (
    <NextHead>
      <title>Contacts</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead>
  )
}